version: '3.7'

services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
